site_name: CRR Project Documentation
nav:
  - Home: index.md
  - Database Documentation: db.md
  - Model Documentation: model.md
plugins:
  
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
