site_name: CRR Project Documentation

theme:
  name: material

nav:
  - Home: index.md
  - Database Documentation: db.md
  - Model Documentation: model.md
  - Data Generator Documentation: generator.md
  - CSV Generator Documentation: GenerateCsv.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]  # This line must be at the same indentation level as 'rendering'
          rendering:
            show_source: true

